language: python
python:
  - "2.7"
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install pep8
# command to run tests
script: 
  - py.test
  - "pep8 --exclude=migrations --ignore=E501,E225 src"